name: 'Setup Python Environment'
description: 'Setup Python 3.13 and install uv'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
